name: validation_queue
description: Composable validation with const support. Queue validators with termination strategies and cross-field validation.
version: 0.1.0
repository: https://github.com/CardosoShlomo/validation_queue

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ui_payload: ^0.1.0

dev_dependencies:
  flutter_lints: ^6.0.0